# -*- coding: utf-8 -*-
"""DA24M015.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gQn3c8CgyhWXikbttCPdffbz4yScy_WV
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
data = pd.read_csv('/content/drive/My Drive/Colab Notebooks/Dataset.csv')
data.columns=['X','Y']
data['X']=data['X'].round().astype(int)
data['Y']=data['Y'].round().astype(int)
print(data.head())

data.size

data.describe()

import matplotlib.pyplot as plt

plt.scatter(data['X'], data['Y'])
plt.title('(Original Image)')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.show()

import numpy as np
matrix=np.zeros((1000,1000),dtype=int)
matrix

"""#Transformation"""

def create_sparse_matrix(data):
    for _,row in data.iterrows():
      x=int(row[0])
      y=int(row[1])
      matrix[x][y] = 1
create_sparse_matrix(data)

print(matrix)

"""#Visualization

1. Rotated image by 90 degree clockwise
"""

row_reverse=np.flipud(matrix)
rotated = np.transpose(row_reverse)
X_coordinates,Y_coordinates=np.where(rotated==1)
plt.scatter(X_coordinates,Y_coordinates)

plt.title('Rotated Image(90 Degrees clockwise)')
plt.xlabel('X')
plt.ylabel('Y')

"""2. Horizontally fliped image"""

column_reverse=np.fliplr(matrix)
X_coordinates,Y_coordinates=np.where(column_reverse==1)
plt.scatter(X_coordinates,Y_coordinates)
plt.title('Horizontally Flipped Image')
plt.xlabel('X')
plt.ylabel('Y')

